const alth = 
[
    "--Select--",
    "Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram",
    "Indian Institute of Information Technology, Allahabad",
    "Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur",
    "Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior",
    "Indian Institute of Information Technology Lucknow",
    "Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh",
    "Indian Institute of Information Technology (IIIT) Nagpur",
    "Indian Institute of Information Technology(IIIT) Kottayam",
    "Indian Institute of Information Technology Bhagalpur",
    "Indian Institute of Information Technology (IIIT) Ranchi",
    "Indian Institute of Information Technology(IIIT), Vadodara, Gujrat",
    "Indian Institute of Information Technology Guwahati",
    "Indian Institute of Information Technology (IIIT) Pune",
    "Indian Institute of Information Technology Bhopal",
    "Indian Institute of Information Technology(IIIT) Una, Himachal Pradesh",
    "Indian Institute of Information Technology(IIIT) Dharwad",
    "Indian Institute of Information Technology Manipur",
    "Indian Institute of Information Technology (IIIT)Kota, Rajasthan",
    "Indian Institute of Information Technology(IIIT) Kilohrad, Sonepat, Haryana",
    "Indian Institute of Information Technology Surat",
    "Indian Institute of Information Technology (IIIT), Sri City, Chittoor",
    "Indian Institute of Information Technology(IIIT) Kalyani, West Bengal",
    "Indian Institute of Information Technology Tiruchirappalli",
    "Indian Institute of Information Technology, Raichur, Karnataka",
    "Indian Institute of Information Technology Srirangam, Tiruchirappalli",
    "Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD)",
    "Indian Institute of Information Technology, Agartala",
    "Indian Institute of Information Technology(IIIT), Sri City, Chittoor District, Andra Pradesh",
    "Indian Institute of Information Technology(IIIT), Sri City, Chittoor District, Andhra Pradesh",
    "Indian Institute of Technology Kharagpur",
    "Indian Institute of Technology (BHU) Varanasi",
    "Indian Institute of Technology Delhi",
    "Indian Institute of Technology Roorkee",
    "Indian Institute of Technology Bombay",
    "Indian Institute of Technology Madras",
    "Indian Institute of Technology Kanpur",
    "Indian Institute of Technology (ISM) Dhanbad",
    "Indian Institute of Technology Bhubaneswar",
    "Indian Institute of Technology Guwahati",
    "Indian Institute of Technology Hyderabad",
    "Indian Institute of Technology Patna",
    "Indian Institute of Technology Ropar",
    "Indian Institute of Technology Mandi",
    "Indian Institute of Technology Jodhpur",
    "Indian Institute of Technology Gandhinagar",
    "Indian Institute of Technology Indore",
    "Indian Institute of Technology Jammu",
    "Indian Institute of Technology Tirupati",
    "Indian Institute of Technology Palakkad",
    "Indian Institute of Technology Dharwad",
    "Indian Institute of Technology Bhilai",
    "Indian Institute of Technology Goa",
    "Indian School of Mines Dhanbad",
    "National Institute of Technology, Rourkela",
    "National Institute of Technology Raipur",
    "National Institute of Technology, Warangal",
    "National Institute of Technology Calicut",
    "National Institute of Technology, Tiruchirappalli",
    "National Institute of Technology Hamirpur",
    "National Institute of Technology Karnataka, Surathkal",
    "Dr. B R Ambedkar National Institute of Technology, Jalandhar",
    "Maulana Azad National Institute of Technology Bhopal",
    "National Institute of Technology Durgapur",
    "Motilal Nehru National Institute of Technology Allahabad",
    "Visvesvaraya National Institute of Technology, Nagpur",
    "National Institute of Technology Agartala",
    "National Institute of Technology Patna",
    "Malaviya National Institute of Technology Jaipur",
    "Sardar Vallabhbhai National Institute of Technology, Surat",
    "National Institute of Technology, Kurukshetra",
    "National Institute of Technology, Srinagar",
    "National Institute of Technology, Andhra Pradesh",
    "National Institute of Technology, Jamshedpur",
    "National Institute of Technology, Silchar",
    "Indian Institute of Engineering Science and Technology, Shibpur",
    "National Institute of Technology Goa",
    "National Institute of Technology Puducherry",
    "National Institute of Technology, Uttarakhand",
    "National Institute of Technology Delhi",
    "National Institute of Technology Arunachal Pradesh",
    "National Institute of Technology, Manipur",
    "National Institute of Technology Meghalaya",
    "National Institute of Technology Nagaland",
    "National Institute of Technology Sikkim",
    "National Institute of Technology, Mizoram",
    "Birla Institute of Technology, Mesra, Ranchi",
    "Indian Institute of Engineering Science and Technology, Shibpur",
    "Punjab Engineering College, Chandigarh",
    "Assam University, Silchar",
    "Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.)",
    "Sant Longowal Institute of Engineering and Technology",
    "School of Engineering, Tezpur University, Napaam, Tezpur",
    "HNB Garhwal University Srinagar (Garhwal)",
    "Mizoram University, Aizawl",
    "Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal",
    "Gurukula Kangri Vishwavidyalaya, Haridwar",
    "Pondicherry Engineering College, Puducherry",
    "International Institute of Information Technology, Bhubaneswar",
    "Puducherry Technological University, Puducherry",
    "Institute of Infrastructure, Technology, Research and Management-Ahmedabad",
    "School of Planning & Architecture, New Delhi",
    "International Institute of Information Technology, Naya Raipur",
    "J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad",
    "School of Planning & Architecture, Bhopal",
    "National Institute of Advanced Manufacturing Technology, Ranchi",
    "School of Planning & Architecture: Vijayawada",
    "Jawaharlal Nehru University, Delhi",
    "Central University of Rajasthan, Rajasthan",
    "Central Institute of Technology Kokrajar, Assam",
    "Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir",
    "North-Eastern Hill University, Shillong",
    "National Institute of Foundry & Forge Technology, Hatia, Ranchi",
    "North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar), Arunachal Pradesh",
    "Birla Institute of Technology, Patna Off-Campus",
    "University of Hyderabad",
    "Central University of Jammu",
    "National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)",
    "Indian Institute of Carpet Technology, Bhadohi",
    "Birla Institute of Technology, Deoghar Off-Campus",
    "Chhattisgarh Swami Vivekananda Technical University, Bhilai (CSVTU Bhilai)",
    "Institute of Chemical Technology, Mumbai: Indian Oil Odisha Campus, Bhubaneswar",
    "Institute of Engineering and Technology, Dr. H. S. Gour University. Sagar (A Central University)",
    "National Institute of Food Technology Entrepreneurship and Management, Sonepat, Haryana",
    "Central University of Haryana",
    "Indian Institute of Handloom Technology(IIHT), Varanasi",
    "Indian Institute of Food Processing Technology, Thanjavur, Tamil Nadu",
    "National Institute of Food Technology Entrepreneurship and Management, Thanjavur",
    "National Institute of Food Technology Entrepreneurship and Management, Kundli",
    "Indian Institute of Handloom Technology, Salem",
    "Indian Institute of Crop Processing Technology, Thanjavur, Tamil Nadu"
];
const gfti = 
[
    "--Select--",
    "ALL",
    "Birla Institute of Technology, Mesra, Ranchi",
    "Indian Institute of Engineering Science and Technology, Shibpur",
    "Punjab Engineering College, Chandigarh",
    "Assam University, Silchar",
    "Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.)",
    "Sant Longowal Institute of Engineering and Technology",
    "School of Engineering, Tezpur University, Napaam, Tezpur",
    "HNB Garhwal University Srinagar (Garhwal)",
    "Mizoram University, Aizawl",
    "Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal",
    "Gurukula Kangri Vishwavidyalaya, Haridwar",
    "International Institute of Information Technology, Bhubaneswar",
    "Puducherry Technological University, Puducherry",
    "Institute of Infrastructure, Technology, Research and Management-Ahmedabad",
    "School of Planning & Architecture, New Delhi",
    "International Institute of Information Technology, Naya Raipur",
    "J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad",
    "School of Planning & Architecture, Bhopal",
    "National Institute of Advanced Manufacturing Technology, Ranchi",
    "School of Planning & Architecture: Vijayawada",
    "Jawaharlal Nehru University, Delhi",
    "Central University of Rajasthan, Rajasthan",
    "Central Institute of Technology Kokrajar, Assam",
    "Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir",
    "North-Eastern Hill University, Shillong",
    "North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar), Arunachal Pradesh",
    "Birla Institute of Technology, Patna Off-Campus",
    "University of Hyderabad",
    "Central University of Jammu",
    "National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)",
    "Indian Institute of Carpet Technology, Bhadohi",
    "Birla Institute of Technology, Deoghar Off-Campus",
    "Chhattisgarh Swami Vivekananda Technical University, Bhilai (CSVTU Bhilai)",
    "Institute of Chemical Technology, Mumbai: Indian Oil Odisha Campus, Bhubaneswar",
    "Institute of Engineering and Technology, Dr. H. S. Gour University. Sagar (A Central University)",
    "Central University of Haryana",
    "Indian Institute of Handloom Technology(IIHT), Varanasi",
    "National Institute of Food Technology Entrepreneurship and Management, Thanjavur",
    "National Institute of Food Technology Entrepreneurship and Management, Kundli",
    "Indian Institute of Handloom Technology, Salem",
];
const iiit = 
[
    "--Select--",
    "ALL",
    "Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram",
    "Indian Institute of Information Technology, Allahabad",
    "Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur",
    "Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior",
    "Indian Institute of Information Technology Lucknow",
    "Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh",
    "Indian Institute of Information Technology (IIIT) Nagpur",
    "Indian Institute of Information Technology(IIIT) Kottayam",
    "Indian Institute of Information Technology Bhagalpur",
    "Indian Institute of Information Technology (IIIT) Ranchi",
    "Indian Institute of Information Technology(IIIT), Vadodara, Gujrat",
    "Indian Institute of Information Technology Guwahati",
    "Indian Institute of Information Technology (IIIT) Pune",
    "Indian Institute of Information Technology Bhopal",
    "Indian Institute of Information Technology(IIIT) Una, Himachal Pradesh",
    "Indian Institute of Information Technology(IIIT) Dharwad",
    "Indian Institute of Information Technology Manipur",
    "Indian Institute of Information Technology (IIIT)Kota, Rajasthan",
    "Indian Institute of Information Technology(IIIT) Kilohrad, Sonepat, Haryana",
    "Indian Institute of Information Technology Surat",
    "Indian Institute of Information Technology (IIIT), Sri City, Chittoor",
    "Indian Institute of Information Technology(IIIT) Kalyani, West Bengal",
    "Indian Institute of Information Technology Tiruchirappalli",
    "Indian Institute of Information Technology, Raichur, Karnataka",
    "Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD)",
    "Indian Institute of Information Technology, Agartala",
];
const iit =
[
    "--Select--",
    "ALL",
    "Indian Institute of Technology Kharagpur",
    "Indian Institute of Technology (BHU) Varanasi",
    "Indian Institute of Technology Delhi",
    "Indian Institute of Technology Roorkee",
    "Indian Institute of Technology Bombay",
    "Indian Institute of Technology Madras",
    "Indian Institute of Technology Kanpur",
    "Indian Institute of Technology (ISM) Dhanbad",
    "Indian Institute of Technology Bhubaneswar",
    "Indian Institute of Technology Guwahati",
    "Indian Institute of Technology Hyderabad",
    "Indian Institute of Technology Patna",
    "Indian Institute of Technology Ropar",
    "Indian Institute of Technology Mandi",
    "Indian Institute of Technology Jodhpur",
    "Indian Institute of Technology Gandhinagar",
    "Indian Institute of Technology Indore",
    "Indian Institute of Technology Jammu",
    "Indian Institute of Technology Tirupati",
    "Indian Institute of Technology Palakkad",
    "Indian Institute of Technology Dharwad",
    "Indian Institute of Technology Bhilai",
    "Indian Institute of Technology Goa",
    "Indian School of Mines Dhanbad"
];
const nit = 
[
    "--Select--",
    "ALL",
    "National Institute of Technology Rourkela",
    "National Institute of Technology Raipur",
    "National Institute of Technology, Warangal",
    "National Institute of Technology Calicut",
    "National Institute of Technology, Tiruchirappalli",
    "National Institute of Technology Hamirpur",
    "National Institute of Technology Karnataka, Surathkal",
    "Dr. B R Ambedkar National Institute of Technology, Jalandhar",
    "Maulana Azad National Institute of Technology Bhopal",
    "National Institute of Technology Durgapur",
    "Motilal Nehru National Institute of Technology Allahabad",
    "Visvesvaraya National Institute of Technology, Nagpur",
    "National Institute of Technology Agartala",
    "National Institute of Technology Patna",
    "Malaviya National Institute of Technology Jaipur",
    "Sardar Vallabhbhai National Institute of Technology, Surat",
    "National Institute of Technology, Kurukshetra",
    "National Institute of Technology, Srinagar",
    "National Institute of Technology, Andhra Pradesh",
    "National Institute of Technology, Jamshedpur",
    "National Institute of Technology, Silchar",
    "Indian Institute of Engineering Science and Technology, Shibpur",
    "National Institute of Technology Goa",
    "National Institute of Technology Puducherry",
    "National Institute of Technology, Uttarakhand",
    "National Institute of Technology Delhi",
    "National Institute of Technology Arunachal Pradesh",
    "National Institute of Technology, Manipur",
    "National Institute of Technology Meghalaya",
    "National Institute of Technology Nagaland",
    "National Institute of Technology Sikkim",
    "National Institute of Technology, Mizoram"
];